services:
  postgres:
    image: postgres:16-alpine
    container_name: fast-food-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fast_food
      POSTGRES_USER: fastfood
      POSTGRES_PASSWORD: fastfood
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fastfood -d fast_food"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: